openapi: 3.0.2
info:
  title: Curate clusters service
  version: 0.0.1
servers:
- url: http://localhost:9090/
paths:
  /clusters/register:
    post:
      tags:
        - CurateClusters
      operationId: registerCluster
      requestBody:
        description: Cluster Controller Metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClusterControllerMetadata'
        required: true
      responses:
        5XX:
          description: unexpected error
        422:
          description: Invalid input
          content: {}
        401: 
          description: Unauthorized
        200: 
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /clusters:
    get:
      tags:
        - CurateClusters
      operationId: listClusters
      responses:
        5XX:
          description: unexpected error
        422:
          description: Invalid input
          content: {}
        401: 
          description: Unauthorized
        200: 
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClusterControllerMetadata"
components:
  schemas:
    ClusterControllerMetadata:
      type: object
      required:
      - id
      - name
      - no_workers
      - no_masters
      properties:
        id:
          type: string
        name:
          type: string
        no_workers:
          type: integer
        no_masters:
          type: integer
        network_plugin:
          type: string
